### ISSUE TITLE
Vsh is not given in 2-compartments_L5-PC_model/SingleNeuron/FIh.m 

### ISSUE THREAD

**Issue by ifgovh** [beaherrera/2-compartments_L5-PC_model#1]
In this line,
https://github.com/beaherrera/2-compartments_L5-PC_model/blob/67ea0fdae92abae6850232532716c2d89c3251b9/SingleNeuron/FIh.m#L70
the variable Vsh is not given. 

Error trace:
Unrecognized function or variable 'Vsh'.

Error in FIh (line 70)
E_NaD = 50 + Vsh; % [mV] reversal potatial for the sodium channels

Error in mainIh>@(X)FIh(0,X,theta) (line 191)
X0 = fsolve(@(X)FIh(0,X, theta), X0);

Error in fsolve (line 258)
            fuser = feval(funfcn{3},x,varargin{:});

Error in mainIh (line 191)
X0 = fsolve(@(X)FIh(0,X, theta), X0);

Caused by:
    Failure in initial objective function evaluation. FSOLVE cannot continue.
 
Could you please add its value to make it run correctly? Thank you.

**Comment by beaherrera** [comment]
Hello,

I fixed the issue. Vsh is equal to 0. I removed it from FIh.m and FnoIh.m.  

Thank you,
Beatriz
